SELECT DISTINCT CITY FROM STATION
WHERE CITY REGEXP '^[aeiou]' AND
(CITY LIKE '%a' OR 
 CITY LIKE '%e' OR 
 CITY LIKE '%i' OR 
 CITY LIKE '%o' OR 
 CITY LIKE '%u');

/*
SELECT DISTINCT CITY FROM STATION
WHERE CITY REGEXP '^[aeiou].*[aeiou]$';
*/
